# Groq API Keys
GROQ_API_KEY_RAPID_CHAT = ''
GROQ_API_KEY_COURSES = ''
GROQ_API_KEY_COURSE_PODCAST = ''
GROQ_API_KEY_COURSE_EXAM = ''
GROQ_API_KEY_COURSE_EMBED = ''
GROQ_API_KEY_COURSE_CHAT = ''

# Play API Credentials
USER_ID = ''
SECRET_KEY = ''